# Generated by Django 5.1.3 on 2024-11-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=64)),
                ('item_code', models.IntegerField()),
                ('description', models.TextField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
    ]
